name: untitled1
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  excel: ^4.0.0
flutter:
  assets:
    - assets/concrete_data.xlsx


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

